### ISSUE TITLE
[Feature Request] support long screen(18:9 aspect ratio)

### ISSUE THREAD

**Issue by spike-bepop** [quasarframework/icongenie#102]
Under screen which has an aspect ratio of 18:9, the background image will be stretched vertically.

**Comment by TomDeSmet** [comment]
I have the same problem. Tested it on a Pixel 2 and the splashscreen was correct, but on a Samsung 8 it was stretched.

**Comment by rstoenescu** [comment]
Tried to address this with Icon Genie v2 (to be released soon). In any case, custom profiles will be available for Icon Genie v2 if I missed anything.
