### ISSUE TITLE
icon-genie zopfli can be further improved

### ISSUE THREAD

**Issue by jitendra1607** [quasarframework/icongenie#103]
Please see on screenshot that icons generated by icon-genie with zopfli compression can be further compressed to 50% without quality sacrifice.
Please try to inbuilt this into icon-genie.

![alt text](https://i.postimg.cc/fWV1SBjW/Screen-Shot-2020-02-16-at-10-04-50.png)

**Comment by rstoenescu** [comment]
This ticket will be obsolete with the complete rewrite of Icon Genie v2.
