### ISSUE TITLE
Use a media query to select correct splash screen for iOS

### ISSUE THREAD

**Issue by tohagan** [quasarframework/icongenie#109]
All the good oil is demo'd here ... 
- https://appsco.pe/developer/splash-screens

I think image sizes needed for this are larger than current source image for Icon Genie.
Another reason to support SVG as an optional input source format.

**Comment by rstoenescu** [comment]
This will go into the complete rewrite of Icon Genie v2.

**Comment by tohagan** [comment]
Awesome!  Thank you. Thank you!

**Comment by rstoenescu** [comment]
iOS pwa splashscreen will be available with Icon Genie v2.
