### ISSUE TITLE
core-js dependency not found

### ISSUE THREAD

**Issue by mattaniah** [quasarframework/icongenie#112]
I am seeing quasar commands fail (dev / build) with errors indicating core-js dependencies were not found.

This can be reproduced by creating a clean quasar project, then installing the icon-genie extension.

Removing the icon-genie extension resolves these errors.

I have done some brief checking into similar areas.  Other similar issues point to a core-js@2 vs core-js@3 versioning issue.

**Comment by mattaniah** [comment]
Closing, duplicates issue #110

**Comment by mattaniah** [comment]
Re-opening. This behavior persists on nodeJS v12.16.1

**Comment by mattaniah** [comment]
This appears to be a core-js dependency issue. Investigating whether babel version changes to quasar app have created a dependency mismatch.

**Comment by benjidotsh** [comment]
I'm having exactly the same problem

**Comment by hawkeye64** [comment]
@mattaniah @benjiJanssens See resolution in this thread: https://github.com/quasarframework/quasar/issues/6458#issuecomment-606620340
