### ISSUE TITLE
Generating empty file for screen-xxhdpi-landscape

### ISSUE THREAD

**Issue by customautosys** [quasarframework/icongenie#113]
Recently I updated icon-genie and the upgrade seems to have broken something. It replaces src-cordova/res/screen/android/screen-xxhdpi-landscape with an empty file when building for release. This causes the cordova release build to fail with an error "src-cordova/platforms/android/app/src/main/res/drawable-land-xxhdpi/screen.png: error: failed to read PNG signature: file does not start with PNG signature".

**Comment by rstoenescu** [comment]
This will be obsolete with the complete rewrite of Icon Genie v2.
