### ISSUE TITLE
Splash Screen errors: UnhandledPromiseRejectionWarning

### ISSUE THREAD

**Issue by kevinXmichael** [quasarframework/icongenie#114]
When I create new quasar app and install the icon-genie extension (or even install it separately via npm) and then run the app in dev mode or build it, I get the following error message when trying to generate the splash-screen files:

**(node:52019) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'background_color' of undefined**
    at Object.splash (/usr/local/lib/node_modules/@quasar/quasar-app-extension-icon-genie/lib/index.js:408:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/@quasar/quasar-app-extension-icon-genie/bin/cli.js:104:15)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1025:10)
    at internal/main/run_main_module.js:17:11
(node:52019) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:52019) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

I used the following command separately:
`$ icongenie -p=splash -s app-splashscreen.png -t ./ -m=pngquant`
(My target is the project-root, where `src-capacitor` is located)

Unfortunately the icon-genie currently only works with the following quick-fix:
`$ yarn add -D core-js@2.6.5`

---
ProductName:	Mac OS X
ProductVersion: 10.15.4
BuildVersion: 19E266
node-version: v12.12.0

**Comment by kmschott** [comment]
`yarn add -D core-js@2.6.5`

will fix the problem, but is this a "good" solution?

**Comment by kmschott** [comment]
Generating splash-screen-icons seems also to be broken 🧐

**Comment by rstoenescu** [comment]
This will become obsolete with the complete rewrite of Icon Genie v2.

**Comment by kevinXmichael** [comment]
@rstoenescu When will Icon Genie v2 be released?

**Comment by rstoenescu** [comment]
This week.

**Comment by kevinXmichael** [comment]
Thats amazing! Thx
