### ISSUE TITLE
'@quasar/icon-genie@latest' is not in the npm registry.

### ISSUE THREAD

**Issue by agaplus** [quasarframework/icongenie#115]
After upgrade quasar with "quasar upgrade -i", the cmd give me this result:
 E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@quasar%2ficon-genie - Not found
npm ERR! 404
npm ERR! 404  '@quasar/icon-genie@latest' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

**Comment by rstoenescu** [comment]
There is no `@quasar/icon-genie`. There's only the `@quasar/quasar-app-extension-icon-genie`...
