### ISSUE TITLE
An idea for generating background images.

### ISSUE THREAD

**Issue by tohagan** [quasarframework/icongenie#116]
Another missing feature that's already been mentioned is gradient backgrounds.  The other bit that complements this is shadows and also very long shadows (stretching to the edge of the app icon or splash image) using an SVG icon as the source.  Combine these and you've covered most of the graphics used for modern app icon/ app splash images.

Idea: If you used HTML canvas to generate them you could use the CSS engine to create many different background styles and the door is open for coders to create more.  
- e.g. `background: radial-gradient(circle, #35a2ff 0%, #014a88 100%)`

Now allow use of the predefined CSS variables from your project and changing theme colors or even fonts in your app icons is a snap!

**Comment by tohagan** [comment]
Another trick this then opens up is using SVG background tiles.
Here's some free ones - https://www.heropatterns.com/

I don't think you'd need to code this once you have HTML to generate the backgrounds.
It just opens the door to more possibilities of which this is just one. 
Would be cool in the demo though!

- and more ... https://www.sitepoint.com/6-incredible-svg-pattern-generators/

**Comment by rstoenescu** [comment]
Hi,

I think we're diverging from the point of Icon Genie's existence. This is a tool to create icon files and splashscreens. I read about CSS and canvases here -- there's no connection between that and Icon Genie's purpose.

**Comment by tohagan** [comment]
I meant using HTML/CSS for **generating the background images** that are placed behind the final icons and splash screens.  You might use something like https://github.com/bubkoo/html-to-image for this. 

The reason for using HTML/CSS is that 
  1. Quasar devs are like to be very familiar with CSS rules.
  2. Can be responsive to the required icon or splash image size 
       (e.g. tiling or shadows adjust for each splash screen size required)  
  3. You could use quasar theme CSS vars to compute the colors. 

Even just having a means to select a background image (rather than a flat image color) would be great!

**Comment by tohagan** [comment]
If I'm ever not making sense ... just ping me.
