### ISSUE TITLE
Add option to suppress verbose console output

### ISSUE THREAD

**Issue by plutonik00** [quasarframework/icongenie#82]
In build tools the progress indicator can lead to many log lines with various states of the spining indicator that is used to indicate process. It would be nice to have an option to turn that indicator off.

**Comment by drasill** [comment]
Yes, this is especially annoying in CI :
![cap-04-2xaoût](https://user-images.githubusercontent.com/968741/63843784-42ccd980-c987-11e9-980e-0672fb6c12e6.png)
... and tens of lines after that.

**Comment by rstoenescu** [comment]
This will be obsolete with the complete rewrite of Icon Genie v2.
