### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by louisameline** [quasarframework/icongenie#83]
Hi,

I tried the genie today, I wanted to leave some feedback.

1. Thank you for your work :)
1. The wizard is currently run during the installation. For some reason I had to quit during the questions, so then I was like "ok, how do I launch the wizard again? And where is that `quasar.extensions.json` file that I can't find?". It turns out the install was only partially completed, so I had to uninstall and reinstall the extension. So I wish the wizard were launched only after a proper installation, by writing a dedicated command. It would allow to launch it several times if need be, or just skip it entirely.
1. The "select with the keyboard arrows" does not work for me. I use Mintty on Windows. I had to delete the `>` sign by hand and write another on a line below, never had to do that before. Also, the way I'm supposed to enter the color later is unclear (maybe just in Mintty?), am I supposed to type directly where the pointer is, or delete the existing color in place?
![image](https://user-images.githubusercontent.com/371814/63183306-f57e6d00-c054-11e9-9b42-a90222bc9a21.png)
1. `Always rebuild?`: it should be clear in the wizard that even if I click "No", it will still be rebuilt whenever I change my image. I had to dig in the docs to make sure it was the case. By the way I would add a mention about this in the "triggering" section of the doc, because it's only mentioned two sections lower and you don't see it right away when you're skimming the doc.
1. Maybe the docs should be structured according to the wizard: everything you need to know to answer question 1, then everything about question 2... Right now the info is scattered, for example the docs explain the build strategy before the minify strategy, while the wizard asks about the minify strategy first.
1. I tried to launch a build of icons through the CLI, so I saw I was supposed to write something like `icongenie -p=kitchensink -s=icon-1280x1280.png -t=./outputFolder -m=pngquant` and I was really confused. Why is there only one file for source when there are two if we provide the splashscreen? Why does it ask for one output folder when the files are supposed to be created automatically in the right places? Are we talking about the root of my project?
1. The above mentioned command returned nothing, there were no error messages and as far as I can tell it did nothing. I gave up that CLI idea.
1. Is it normal that a file is called `screen-iphone-portrait-568h_2x.png` with an underscore in `res/screen/ios` while the rest uses hyphens?
1. The generated icons were a double failure for me because of how my assets are designed, but I'll create two separate issues for that.

I'm sure the genie is going to be awesome when it's ready! But right now it came short in my use case and it didn't go like a breeze yet.

Thank you!

**Comment by nothingismagick** [comment]
I can tell you that its ready and in use in many projects right now. The only way I could envision accommodating obviously posix-non-compliant terminal emulators like "Mintty on Windows" might be to allow for ingestion of a settings file. I'll need to think about that - and that is likely to be something to solve at the @quasar/app App Extension API interface.

If you are interested in helping revise the docs, then I am always open to PRs. It's open source and a community project. This project has been underway for a very long time.

**Comment by nothingismagick** [comment]
regarding the underscore, you're right.
prefix: 'screen-iphone-portrait-568h_2x',
should be:
prefix: 'screen-iphone-portrait-568h-2x',

**Comment by louisameline** [comment]
Thank you for the reply. I actually don't care for a wizard, setting up the json file is just as fine. I just wish that quitting the wizard didn't actually abort the installation silently though, being able to launch it separately would fix that.

And what do you make of these points: 2, 6, 7? Did I miss something obvious? Thank you

**Comment by nothingismagick** [comment]
2. Well, as you get to know more about the App Extension system, you'll notice that you don't have to Uninstall them to run them again. The quasar.extensions.json only exists AFTER a completed run of an app extension install.
6 /7 . Regarding the CLI, that is not the primary interface for the Icon Genie, but I'll look into what's going on there. It should at least tell you what's going on.

**Comment by louisameline** [comment]
2 - I added the extension again to rerun the wizard and finish the install but if there's  a command for that, it would be great to have it mentioned in the genie doc. The genie is likely to be the most used extension, it might be a good place to tell a couple useful things about them if need be.

And that's my point for the wizard, I wish there was a complete installation with default config values, and then we'd run the wizard with a second command line for those who can/want to do it. I guess a lot of people would be happy with default values (optipng, not rebuild every time...) and might be better off not having to answer these questions at all. You'd install and it would just work, no questions asked. Then if you want/need to customize/optimize you dig in. Just my 2 cents on what I'd like as a smooth experience with the genie, but you might not agree.

6-7 - Ok thank you

**Comment by rstoenescu** [comment]
The `screen-iphone-portrait-568h_2x` underscore issue has been fixed in the complete rewrite of Icon Genie v2.
The other problems will become obsolete. Stay tuned.
