### ISSUE TITLE
Feature request: be able to provide a specific image for landscape mode

### ISSUE THREAD

**Issue by louisameline** [quasarframework/icongenie#84]
Currently, we have to provide a single square image that will be used both for portrait and landscape modes.

However that only works if the logo is in the middle of the image.

In my case the center of my image is empty because I display both my logo and the name of my app, as on the picture below. Beside the fact that I like it that way, one the advantages of doing this is that Cordova's spinner at load doesn't overlap with my logo as shown on this screenshot:

![image](https://user-images.githubusercontent.com/371814/63209731-26a67e00-c0e5-11e9-85af-e9542df90217.png)

My picture is fine when cropped by the genie in portrait but not in landscape: 

![image](https://user-images.githubusercontent.com/371814/63209750-6ff6cd80-c0e5-11e9-8204-ab7f2174e43d.png)

So I'd like to be able to provide a landscape-specific version of my image.
What do you think? Thank you

**Comment by rstoenescu** [comment]
This will be possible with the complete rewrite of Icon Genie v2 (by using multiple profile files).
