### ISSUE TITLE
Feature request: be able to provide a specific no-opacity version of the logo

### ISSUE THREAD

**Issue by louisameline** [quasarframework/icongenie#85]
My logo looks like this: 

![image](https://user-images.githubusercontent.com/371814/63209824-23f85880-c0e6-11e9-993f-d2b02a6387b5.png)

With the outer shadow and gradient, it doesn't work to just use a plain background color in lieu of transparency. I need to be able to provide a specific no-opacity version of the logo myself for iOS, and not let the genie try to "fix" my transparent logo like this:

![image](https://user-images.githubusercontent.com/371814/63210373-e13a7e80-c0ed-11e9-9ff4-1f6a3aada92b.png)

What do you think? Thank you

**Comment by nothingismagick** [comment]
You need to tell me what you are targeting. I assume you mean Cordova - I
forget which one it is, but I think iOS prevents you from having
transparent backgrounds for some reason.

>

**Comment by mesqueeb** [comment]
@louisameline since iOS doesn't support transparency just set `#ffffff` for the background colour during the icon-genie initialisation. ;)

**Comment by louisameline** [comment]
No, my goal is to provide a logo that will not feature a circle container, only the logo on a colored background. Thank you

**Comment by nothingismagick** [comment]
There is no circle container applied by icon-genie

>

**Comment by louisameline** [comment]
Sure, the circle is mine, but it should be present only on images that have transparency. Hence the need for me to provide two separate images.

**Comment by mesqueeb** [comment]
So basically you want to provide a different icon for Android (where transparency is supported) and iOS (where it is not )
That would be a nice feature I think so too, At least if that's what you mean.

**Comment by louisameline** [comment]
Yes that is right.

**Comment by rstoenescu** [comment]
@louisameline This will be possible with the complete rewrite of Icon Genie v2. Individual modes can be generated with different options. And also multiple profile files can be used to automate everything.
