### ISSUE TITLE
Disable building icons for dev.

### ISSUE THREAD

**Issue by mesqueeb** [quasarframework/icongenie#86]
I'm a little bit confused about the dual icon generation for both `dev` and `build` commands.

In all my projects I work on I usually have this work flow:
- develop on dev branch
- merge dev into master for a public release

Before a public release I'd have to do `quasar build` to make sure to have the `dist` folder and have the icons in the better quality.

However, after the dev branch is merged and I continue developing, `quasar dev` will trigger icon-genie again and overwrite those better quality icons with the lower ones.

I'm not sure if I'm using it correctly, but when the icons are built for production once, as long as the icon stays the same, I'd feel like it's OK for the dev server to just continue using the production ones... Having an extra build step for the icons that already exist again, and having to commit them to the git history again seems strange.

I could try setting both dev and production to the "better quality" icon setting of icon-genie, but this seems like not what's supposed to be.

Am I missing something? 😄 

Is it possible to "disable" icon-genie on dev and just have the icons generated once on a manual `quasar build` trigger? Or is there a reason this is not recommended? 🤔

**Comment by mesqueeb** [comment]
I was able to get around this by just setting both `production` and `development` icon qualities to the same quality. This prevents the icons from being re-generated every single time you alternate between `quasar build` and `quasar dev`.
😉

**Comment by IlCallo** [comment]
Came here for the same reason. Is it possible to understand which icon quality is currently in use and in case avoid rebuilding if better quality icons are already in place?

**Comment by mesqueeb** [comment]
@IlCallo if you set it to highest quality for both Dev and Prod it will only build once and never again.

**Comment by IlCallo** [comment]
Yes, already did it, I was trying to find new solutions

**Comment by rstoenescu** [comment]
This will be obsolete with the complete rewrite of Icon Genie v2.
