### ISSUE TITLE
Feature request: different icons per mode/platform

### ISSUE THREAD

**Issue by GordonBlahut** [quasarframework/icongenie#91]
For my SPA and Android app I might want an icon with rounded edges, but since iOS already forces all icons to have rounded edges, this can lead to some conflicts if the icon provided has transparency at the edges or the rounding used is larger than Apple's. Or I may just want to make my icons better match platform-specific aesthetic. 

Basically, the ability to provide source icons like **app-icon.cordova.ios.png**, **app-icon.cordova.android.png**, etc. with fallback to **app-icon.png** if a platform/mode-specific icon isn't provided.

**Comment by GordonBlahut** [comment]
Actually, rather than specific icon names, allow devs to set the source icon paths/names in quasar.conf.js. That way we can use any logic we want (e.g. checking ctx.dev, ctx.mode.cordova, ctx.targetName, etc.) to set the source icons. That way any variations could be accommodated like if someone wanted a different icon for dev vs build.

The cached hash for icons would probably have to be keyed by the file name/path.

**Comment by spike-bepop** [comment]
> allow devs to set the source icon paths/names in quasar.conf.js

+1

**Comment by Nigui** [comment]
+1 👍

**Comment by hawkeye64** [comment]
@GordonBlahut @evazc @Nigui Check this out for a reply: https://github.com/quasarframework/app-extension-icon-genie/issues/108#issuecomment-605631892

**Comment by rstoenescu** [comment]
This will be available with the complete rewrite of Icon Genie v2.
