### ISSUE TITLE
Wrong source images reference across separate packages

### ISSUE THREAD

**Issue by alexeigs** [quasarframework/icongenie#99]
I have two distinct apps in two sibling folders with a "root level" each including their own package.json, quasar.conf, app-icon.png, quasar.extensinos.json etc.
Now, when I run the development server or build the package (e.g. `.../app1 $quasar run dev/build`), it happens that it references the `app-icon.png` from the other app 2 although I run the command inside app 1. Why does this happen?

Also I cannot find the cache, so even when removing all `app-icon-DARK.png` from the whole code base, it keeps generating dark icons although there are now only `app-icon-LIGHT.png` left.

How do these things play together? How can I reference the right source image when building app1 or app2 and/or how can I clear the cache at least?

**Comment by alexeigs** [comment]
Is there, as a workaround, an easy way to just disable new generation of icons completely? Or do I need to remove it from `quasar.extensions.json`?

**Comment by rstoenescu** [comment]
This will be obsolete with the complete rewrite of Icon Genie v2.
